### ISSUE TITLE
Conversation not deleted

### ISSUE THREAD

**Issue by fantasio31** [nextcloud/ocsms#179]
### Steps to reproduce
1. Open OCSMS in Nextcloud
2. Remove a conversation
3. Change application in Nextcloud
4. Open OCSMS in Nextcloud again

### Expected behaviour
Conversation should not be displayed anymore

### Actual behaviour
Conversation appears again in the list including all messages

### Server configuration

NextCloud version: 11.0.2

PHP version: 5.6

HTTPd server: Apache 2.4

### Logs
Logs are similar to the ones of issue #178 .

**Comment by fantasio31** [comment]
Here is status with nextcloud 12.0.4 and ocsms 1.12.2.
![2018-01-09 09_51_44-administration - logs](https://user-images.githubusercontent.com/23166621/34713205-d375c9ac-f525-11e7-92d6-4e3c0e33e6e1.jpg)

**Comment by nerzhul** [comment]
Hello
thanks for your report. The logs you give us aren't related to this app

**Comment by nerzhul** [comment]
@prilly do you have some logs to give us ?
Can you update to 1.12.5 and retry ?

**Comment by hugofant** [comment]
Hi,
i'm running NC 13.0.2 and PhoneSync 1.12.6 and delete is not possible.
Log shows:

Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'DELETE FROM oc_ WHERE (user_id = ?) AND (sms_address = ?)' with params ["xxxxxxx", "yyyyyyy"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'privdata_mynextcloud.oc_' doesn't exist

(Params have been replaced)

**Comment by nerzhul** [comment]
WTF is that bug, it seems the table name is empty... let me look at this

**Comment by nerzhul** [comment]
the code is the following

```php
$qb->delete()
			->from('ocsms_smsdatas')
			->where($qb->expr()->andX(
				$qb->expr()->eq('user_id', $qb->createNamedParameter($userId)),
				$qb->expr()->eq('sms_address', $qb->createNamedParameter($phoneNumber))
			)
			);
```

**Comment by nerzhul** [comment]
okay i see the problem, the delete query is false. Will fix it

**Comment by nerzhul** [comment]
can you patch your code with the following commit and tell me if that works ?

14fefaeedd408dfec25e83d716718feb9ba6df04

i don't have a correct dev environment atm but it should work

**Comment by hugofant** [comment]
done - Works like a charm

**Comment by nerzhul** [comment]
perfect, sorry for the problems :) i release 1.12.7... yeah my dev cycle i not very strict these days, and i'm sorry :)
also the forced changes using the query builder take some time as this app is very linked to the db

**Comment by fantasio31** [comment]
Issue is not resolved on my installation with 1.12.7 : 


Error | index | Doctrine\DBAL\Exception\TableNotFoundException: An  exception occurred while executing 'DELETE FROM `oc_` WHERE (`user_id` =  ?) AND (`sms_id` = ?)' with params ["gaetan", 18904]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table  'nextcloud.oc_' doesn't exist/var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128:  Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))/var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 1015:   Doctrine\DBAL\DBALException   driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver),  Object(Doctrine\DBAL\Driver\PDOException), 'DELETE FROM `oc...', Array)/var/www/html/nextcloud/lib/private/DB/Connection.php - line 216:  Doctrine\DBAL\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)/var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php - line 208:  OC\DB\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)/var/www/html/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 214:  Doctrine\DBAL\Query\QueryBuilder->execute()/var/www/html/nextcloud/apps/ocsms/db/smsmapper.php - line 341:  OC\DB\QueryBuilder\QueryBuilder->execute()/var/www/html/nextcloud/apps/ocsms/controller/apicontroller.php - line 85:  OCA\OcSms\Db\SmsMapper->writeToDB('gaetan', Array)[internal function] OCA\OcSms\Controller\ApiController->push(42, Array)/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161:  call_user_func_array(Array, Array)/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91:  OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\OcSms\Controller\ApiController), 'push')/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 115:  OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\OcSms\Controller\ApiController), 'push')/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:  OC\AppFramework\App  main('ApiController', 'push', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)/var/www/html/nextcloud/lib/private/Route/Router.php - line 297:  call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)/var/www/html/nextcloud/lib/base.php - line 999:  OC\Route\Router->match('/apps/ocsms/pus...')/var/www/html/nextcloud/index.php - line 37:  OC  handleRequest(){main}
-- | -- | --

**Comment by nerzhul** [comment]
re-opening the ticket, i will try to fix that asap, i need to finish some other work before

**Comment by nerzhul** [comment]
It works properly on latest release.
