### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by freeeflyer** [nextcloud/ocsms#197]
### Steps to reproduce
1. Migrate your owncloud to nextcloud
2. 
3.

### Expected behaviour
Displays correspondants & messages

### Actual behaviour
Can display correspondants list, but no message
### Server configuration

**NextCloud/ownCloud version:**
12.0.1
**PHP version:**
libapache2-mod-php7.0              7.0.21-1~ubuntu14.04.1+deb.sury.org+1**HTTPd server:**

**Database engine & version:** 
postgresql-9.1                     9.1.14-0ubuntu0.12.04

### Client configuration

**Android version:**
6.0
**Phone:**
ZTE Axon 7
**NextCloud SMS app version:**
1.1.0
### Logs

{"reqId":"TO0bEXRJBr9dDiWPC3ro","level":3,"time":"2017-08-15T14:38:02+00:00","remoteAddr":"83.201.122.65","user":"freeflyer","app":"index","method":"GET","url":"\/index.php\/apps\/ocsms\/front-api\/v1\/conversation?phoneNumber=%2B33668080067","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Authenticated ciphertext could not be decoded.\",\"Code\":0,\"Trace\":\"#0 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/apps2\\\/ocsms\\\/db\\\/configmapper.php(68): OC\\\\Security\\\\Crypto->decrypt(*** sensitive parameters replaced ***)\\n#1 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/apps2\\\/ocsms\\\/db\\\/configmapper.php(81): OCA\\\\OcSms\\\\Db\\\\ConfigMapper->getKey('message_limit')\\n#2 \\\/path\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/apps2\\\/ocsms\\\/controller\\\/smscontroller.php(161): OCA\\\\OcSms\\\\Db\\\\ConfigMapper->getMessageLimit()\\n#3 [internal function]: OCA\\\\OcSms\\\\Controller\\\\SmsController->getConversation('+33668080067', 0)\\n#4 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#5 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\OcSms\\\\Controller\\\\SmsController), 'getConversation')\\n#6 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\OcSms\\\\Controller\\\\SmsController), 'getConversation')\\n#7 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('SmsController', 'getConversation', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/ocsms\\\/fro...')\\n#11 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/index.php(48): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/path\\\/to\\\/my\\\/website\\\/www\\\/lib\\\/private\\\/Security\\\/Crypto.php\",\"Line\":119}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/59.0.3100.0 Iron Safari\/537.36","version":"12.0.1.5"}

**Comment by nerzhul** [comment]
it seems your installed app outside apps/ folder

**Comment by freeeflyer** [comment]
Yep, as recommended in nextcloud documentation.

**Comment by freeeflyer** [comment]
There is an array in which you can configure that in the config.php:
<?php

  "apps_paths" => array (
      0 => array (
              "path"     => OC::$SERVERROOT."/apps",
              "url"      => "/apps",
              "writable" => false,
      ),
      1 => array (
              "path"     => OC::$SERVERROOT."/apps2",
              "url"      => "/apps2",
              "writable" => true,
      ),
  ),

URL are hardcoded in "js/public/app.js" i tried to replace "apps" by "apps2" it does not work.. 
But I'm not competent in javascript.

**Comment by nerzhul** [comment]
i see, but now, how properly retrieve app URL from URI with custom folders heh

**Comment by nerzhul** [comment]
i see same problem in news apps: ../news/js/admin/Admin.js:            var url = OC.generateUrl('/apps/news/admin');

**Comment by nerzhul** [comment]
Fixed

**Comment by freeeflyer** [comment]
Hi. Sorry it still does not work here..  (Same kind of messages in the log)

**Comment by nerzhul** [comment]
sounds very strange, it uses the root app URL from browser to generate API calls, can you look your browser console in network tab ?

**Comment by freeeflyer** [comment]
core.js:7 JQMIGRATE: Migrate is installed, version 1.4.0
VM234:674 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-8UwpdwiuqXJty4DoSWEA9W+FMdXW5Ol0a3ZjF7czsyo='), or a nonce ('nonce-...') is required to enable inline execution.

addScript @ VM234:674
VM234:674 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-nC1EIFTfIzbc0hgADWC4Eos+jMRdIaPymHrOT/14N2s='), or a nonce ('nonce-...') is required to enable inline execution.

addScript @ VM234:674
/index.php/apps/ocsms/front-api/v1/conversation?phoneNumber=%2B33611752494 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by nerzhul** [comment]
it seems your server has /app http folder path but you got a 500 error server side, can you look nextcloud logs themselves ?

**Comment by freeeflyer** [comment]
Yep here is the log : 
{"reqId":"42nB0HQzJRA0qBIXxovt","level":3,"time":"2017-08-17T09:53:53+00:00","remoteAddr":"83.201.122.65","user":"freeflyer","app":"index","method":"GET","url":"\/index.php\/apps\/ocsms\/front-api\/v1\/conversation?phoneNumber=%2B33668080067","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Authenticated ciphertext could not be decoded.\",\"Code\":0,\"Trace\":\"#0 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/apps2\\\/ocsms\\\/db\\\/configmapper.php(68): OC\\\\Security\\\\Crypto->decrypt(*** sensitive parameters replaced ***)\\n#1 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/apps2\\\/ocsms\\\/db\\\/configmapper.php(81): OCA\\\\OcSms\\\\Db\\\\ConfigMapper->getKey('message_limit')\\n#2 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/apps2\\\/ocsms\\\/controller\\\/smscontroller.php(161): OCA\\\\OcSms\\\\Db\\\\ConfigMapper->getMessageLimit()\\n#3 [internal function]: OCA\\\\OcSms\\\\Controller\\\\SmsController->getConversation('+33668080067', 0)\\n#4 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#5 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\OcSms\\\\Controller\\\\SmsController), 'getConversation')\\n#6 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\OcSms\\\\Controller\\\\SmsController), 'getConversation')\\n#7 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('SmsController', 'getConversation', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/ocsms\\\/fro...')\\n#11 \\\/path\\\/to\\\/my\\\/website\\\/www\\\/index.php(48): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/path\\\/to\\\/my\\\/website\\\/www\\\/lib\\\/private\\\/Security\\\/Crypto.php\",\"Line\":119}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/59.0.3100.0 Iron Safari\/537.36","version":"12.0.2.0"}

**Comment by nerzhul** [comment]
it's very strange, why does it talk about crypto ? Are you using crypto somewhere ? ocsms doesn't use it

**Comment by freeeflyer** [comment]
Not at all.. I never used crypto.  
Although, line 68 of configmapper.php is : 
```php
return $this->crypto->decrypt($row["value"]);
```

**Comment by nerzhul** [comment]
okay it was me 3 years ago, i think a configuration is wrong in your database maybe look at ocsms_config table content ?

**Comment by freeeflyer** [comment]
Argh my fault. I tried to increase the message number by doing that : 
postgres=# \c owncloud
You are now connected to database "owncloud" as user "postgres".
owncloud=# SELECT * from oc_ocsms_config ;
   user    |      key      | value
-----------+---------------+-------
 freeflyer | message_limit | 5000
(1 row)

..  How should I do it ?

**Comment by nerzhul** [comment]
just drop the key and re-set it using web interface should do the trick

**Comment by freeeflyer** [comment]
done.. works ok :)
Thanks a lot
