### ISSUE TITLE
Can't restore messages

### ISSUE THREAD

**Issue by jkalousek** [nextcloud/ocsms#230]
I just did  factory reset of my phone, after the factory reset I added Nextcloud and NC SMS, checked that syncing to cloud is working and then I went to account and hit Restore all messages (I have it translated to my language so I imagine that it's called something like this in English) I was asked to change default SMS app to NC SMS which I confirmed but then after I hit Restore It flashed something like "SMS restored" for like 0.5 s. And it was done, I changed default app back but there are no messages restored I tried again multiple times but every time It end up same.
I can see few hundred messages synced to my NC but I can't get them back to phone.

Any ideas?

**Android version:** 7

**Phone:** Galaxy S7

**Nextcloud SMS app version:** 2.0.4

(I can't find logs can anyone point me to location)?

**Comment by nerzhul** [comment]
Hello,
it's not the good repo. please open an issue on the android app repository

**Comment by jkalousek** [comment]
Ok sorry I didn't notice its the same problem as https://github.com/nerzhul/ownCloud-SMS-App/issues/198

**Comment by nerzhul** [comment]
Thanks

**Comment by clempar** [comment]
Hi, 
I just got the same issue. 
@nerzhul , as you mentioned in nerzhul/ownCloud-SMS-App#198 , this is a server-side issue, I think this issue should be re-opened. 

I fixed the issue on my server with a quick patch on `db/smsmapper.php` :
```patch
--- db/smsmapper.php.orig     2018-05-12 17:23:03.239463732 +0200
+++ db/smsmapper.php  2018-05-12 17:22:42.194394748 +0200
@@ -157,9 +157,9 @@ class SmsMapper extends Mapper {
                while ($row = $result->fetchRow()) {
                        $messageList[$row["sms_date"]] = array(
                                "address" => $row["sms_address"],
-                               "mailbox" => $row["sms_mailbox"],
+                               "mailbox" => intval($row["sms_mailbox"]),
                                "msg" => $row["sms_msg"],
-                               "type" => $row["sms_type"]
+                               "type" => intval($row["sms_type"])
                        );
                }
                return $messageList;
```
This is not a perfect fix, I have noticed at least one other place where `sms_type` is used and there might be other fields that need this. I don't even know if this is the good way to do it in PHP. 
However this patch was enough so that I could restore my messages, which what I wanted in the first place.

**Comment by nerzhul** [comment]
This is the correct fix, i push it to master and will trigger a release ASAP

**Comment by jkalousek** [comment]
After Update I get error when I click on SMS in Nextcloud:

`ParseError: syntax error, unexpected 'SMS' (T_STRING), expecting ')'`

**Comment by nerzhul** [comment]
i pushed a new release to fix that problem... sorry for the problem, i didn't get time to test the release, i just pushed a PIT release.

**Comment by jkalousek** [comment]
OK, perfect! Thank you both @nerzhul & @clempar.

**Comment by Sigmun** [comment]
I still have this issue even if I use Nextcloud 16 and ocsms 2.1.3. What could I do ?

**Comment by e-alfred** [comment]
@Sigmun Do you get any of the errors shown above? They should be fixed long ago. Maybe your problem is more related to the Android app? 

The repository for it is here: https://github.com/nerzhul/ncsms-android

**Comment by Sigmun** [comment]
I don't know to determine from where it comes but I definitely have the same behavior described in both #230 and #198 
Can you help me to determine what is the error?

**Comment by Sigmun** [comment]
Ok,  sorry for the noise. It seems that my issue is similar to https://github.com/nerzhul/ncsms-android/issues/199 where I've already said that it doesn't work anymore.
Thanks
