### ISSUE TITLE
String at Transifex with unclear meaning

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ocsms#285]
https://github.com/nextcloud/ocsms/blob/7ad26ad4d8378b351c8f643a91bbf45eb8ddea50/l10n/de.js#L5

What is "dwa" about?

Reported at Transifex. See

https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/ocsms/160387981

**Comment by nerzhul** [comment]
wow, what is that ? i don't know where does it comes from

**Comment by rakekniven** [comment]
Yes, that's what I found out. Maybe simply removing it? Recreating source for Transifex again?

**Comment by yarons** [comment]
There are several strings after that which doesn't seem like translation is needed.

This is the list:

    "captured"
    "bubbled"
    "binary"
    "utf-8"
    "a"
    "big"
    "blink"
    "b"
    "tt"
    "font"
    "i"
    "small"
    "strike"
    "sub"
    "sup"

These all look like tags, are you absolutely sure they should be translated?

**Comment by rakekniven** [comment]
Any update on this one?

**Comment by Valdnet** [comment]
I also join the topic. This should be clarified.

**Comment by rakekniven** [comment]
@nerzhul Can you remove the string? Should I create PR for that?

**Comment by nerzhul** [comment]
hello, sorry i'm a little bit busy on other projects. if you can create a PR it's nice

**Comment by nerzhul** [comment]
fixed, thanks

**Comment by rakekniven** [comment]
Looks like no sync to Transifex is done. String is still present.

Please re-open.

**Comment by e-alfred** [comment]
Pretty clear where this comes from, it is stated in Transiflex even: /app/doc/swagger-ui-bundle.js:70

We have to make sure that the bot ignores these files because they are unnecessary for translation.

**Comment by e-alfred** [comment]
Should be fixed by https://github.com/nextcloud/ocsms/commit/0722e70a477ca0c345894b0397d77d81782c7f6e. I would wait for the Next time the nextcloud-bot updates the translations.
