### ISSUE TITLE
NX18 - Could not resolve OCA\\OcSms\\Provider\\FullTextSearchProvider

### ISSUE THREAD

**Issue by hellkaim** [nextcloud/ocsms#320]
I have FTS for Elasticsearch and FTS OCR extensions installed, but disabling or removing them does not help. I can see the search icon in the top navigation panel and even have a form for opening but that is it. Also the build-in search works grate as far as it goes.

The error is as follows:

`{"reqId":"N20lhDojKEgbc3IvDQMD","level":2,"time":"2020-07-18T23:50:51+00:00","remoteAddr":"10.10.10.10","user":"user","app":"fulltextsearch","method":"GET","url":"/apps/fulltextsearch/v1/search?request=%7B%22providers%22%3A%5B%22files%22%5D%2C%22options%22%3A%7B%22files_local%22%3A%221%22%2C%22files_external%22%3A%220%22%2C%22files_extension%22%3A%22%22%7D%2C%22search%22%3A%22new%22%2C%22page%22%3A1%7D","message":"Issue while loading Provider: ocsms/OCA\\OcSms\\Provider\\FullTextSearchProvider - OCP\\AppFramework\\QueryException Could not resolve OCA\\OcSms\\Provider\\FullTextSearchProvider! Class OCA\\OcSms\\Provider\\FullTextSearchProvider does not exist","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0","version":"18.0.7.1"}`

Please feel free to request any additional info needed.

P.S. FTS closed the issue [#95](https://github.com/nextcloud/files_fulltextsearch/issues/95) with the note that it is OcSms related

**Comment by hellkaim** [comment]
Ok, digging a bit I found that the issue is that the class is not populated properly for some reason

Seems like [provider/FullTextSearchProvider.php](https://github.com/nextcloud/ocsms/blob/master/provider/FullTextSearchProvider.php) has all needed code for the class to be there.

Also [appinfo/info.xm](https://github.com/nextcloud/ocsms/blob/master/appinfo/info.xml) has a definition for it...
Still can't understand why FullTextSearch is not using it...

**Comment by hellkaim** [comment]
Update to NC20 is not solve the issue.

**Comment by e-alfred** [comment]
The line at 12 has the wrong app name for the namespace:

https://github.com/nextcloud/ocsms/blob/a9f572c9f3a517531003a90b2efd874e9b652f32/provider/FullTextSearchProvider.php#L12

**Comment by e-alfred** [comment]
Should be fixed by https://github.com/nextcloud/ocsms/commit/feb521ec103d02f5438bc20f31153fbd3712e512.

**Comment by hellkaim** [comment]
Indeed. But the error is still there...

`{"reqId":"uhgLg7BqRMd982vLcMEY","level":2,"time":"2020-12-25T02:55:01+00:00","remoteAddr":"10.8.0.1","user":"XXX","app":"fulltextsearch","method":"GET","url":"/apps/fulltextsearch/v1/search?request=%7B%22providers%22%3A%22all%22%2C%22options%22%3A%7B%22files_local%22%3A%220%22%2C%22files_external%22%3A%220%22%2C%22files_extension%22%3A%22%22%7D%2C%22search%22%3A%22Sabadell.+Recuerde+cambiar+su+clave+de+acceso+a+Banca+a+Distancia.+Puede+hacerlo+desde+la+app%22%2C%22page%22%3A1%7D","message":"Issue while loading Provider: ocsms/OCA\\OcSms\\Provider\\FullTextSearchProvider - OCP\\AppFramework\\QueryException Could not resolve OCA\\OcSms\\Provider\\FullTextSearchProvider! Class OCA\\OcSms\\Provider\\FullTextSearchProvider does not exist","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36","version":"18.0.11.2"}
`
